/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mjaroslav.bon2gradle;

import com.github.mjaroslav.bon2gradle.test.functional.GradleUtils;
import com.github.mjaroslav.bon2gradle.test.shared.IOUtils;
import lombok.val;
import org.gradle.testkit.runner.GradleRunner;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.File;
import java.io.IOException;

import static com.github.mjaroslav.bon2gradle.test.shared.TestConstants.PACKAGE;
import static org.junit.jupiter.api.Assertions.assertTrue;

class Bon2GradleExtensionFunctionalTest {
    @TempDir
    File projectDir;

    private File getBuildFile() {
        return new File(projectDir, "build.gradle");
    }

    @Test
    void test$canRunTask() throws IOException {
        // TODO: FIX THIS ANOTHER RUN DEPENDENCY
        GradleUtils.initBaseForgeGradle12Project(projectDir);
        val runner = GradleRunner.create();
        runner.withPluginClasspath();
        var script = IOUtils.readStringFromResources(PACKAGE + "Bon2GradleExtensionBuild.gradle");
        script = String.format(script, GradleUtils.getClasspathString(runner));
        IOUtils.writeString(getBuildFile().toPath(), script);
        runner.forwardOutput();
        runner.withArguments("dependencies", "--stacktrace");
        runner.withProjectDir(projectDir);
        val result = runner.build();
        assertTrue(result.getOutput().contains("BUILD SUCCESS"));
    }
}
