/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.mjaroslav.bon2gradle;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

public class Bon2GradlePlugin implements Plugin<Project> {
    private Project project;

    public void apply(Project project) {
        this.project = project;
        project.afterEvaluate(project1 -> {
            if (project1.getState().getFailure() != null) return;
            afterEvaluate();
        });
    }

    private void afterEvaluate() {

    }
}
